import {
  Header,
  SectionTitle,
  CtaBanner,
  IntroCopy,
  PromoBlock,
  Footer,
  TwoColStacked,
  OneColProduct,
  OrderCard,
  TwoColDualCta,
  ThreeColIcon,
  HeroBanner,
  Divider,
  ButtonRow,
  ImageBlock,
  Testimonial,
  TextBlock,
  Spacer,
  StatsRow,
} from '@/components/email';
import type { ComponentDefinition } from './types';
import {
  NISSAN_IMAGES,
  NISSAN_COLORS,
  NISSAN_PRODUCT_DEFAULTS,
  NISSAN_SOCIAL_ICONS,
} from '@/lib/constants/nissanAssets';

export const componentDefinitions: ComponentDefinition[] = [
  {
    id: 'header',
    name: 'Header',
    category: 'layout',
    description: 'Logo header with optional link',
    version: 1,
    component: Header,
    defaultProps: {
      logoSrc: NISSAN_IMAGES.logo,
      logoWidth: 250,
      logoAlt: 'Nissan Motor Corporation',
      logoUrl: 'https://www.nissan.com',
      backgroundColor: NISSAN_COLORS.white,
      deskPadding: '25px 40px',
      align: 'center',
    },
    fields: [
      { key: 'logoSrc', label: 'Logo URL', type: 'image', required: true, group: 'Content' },
      { key: 'logoWidth', label: 'Logo Width', type: 'number', group: 'Layout' },
      { key: 'logoAlt', label: 'Alt Text', type: 'text', group: 'Content' },
      { key: 'logoUrl', label: 'Logo Link', type: 'url', group: 'Content' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
      { key: 'deskPadding', label: 'Padding', type: 'text', group: 'Layout', advanced: true },
    ],
  },
  {
    id: 'section-title',
    name: 'Section Title',
    category: 'layout',
    description: 'Section heading divider',
    version: 1,
    component: SectionTitle,
    defaultProps: {
      title: 'Section Title',
      backgroundColor: '#f7f8f8',
      textAlign: 'center',
      fontSize: '24px',
      fontWeight: 700,
      color: '#000000',
      textTransform: 'uppercase',
      letterSpacing: '2px',
    },
    fields: [
      { key: 'title', label: 'Title', type: 'text', required: true, group: 'Content' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
      { key: 'textAlign', label: 'Alignment', type: 'select', group: 'Layout', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ]},
      { key: 'color', label: 'Text Color', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'intro-copy',
    name: 'Intro Copy',
    category: 'newsletter',
    description: 'Greeting and introductory body text',
    version: 1,
    component: IntroCopy,
    defaultProps: {
      greeting: 'Hello,',
      body: 'Welcome to our newsletter.',
      backgroundColor: '#ffffff',
      deskPadding: '30px 40px 20px 40px',
      textAlign: 'left',
    },
    fields: [
      { key: 'greeting', label: 'Greeting', type: 'richtext', group: 'Content' },
      { key: 'body', label: 'Body', type: 'richtext', group: 'Content' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
      { key: 'textAlign', label: 'Alignment', type: 'select', group: 'Layout', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ]},
    ],
  },
  {
    id: 'promo-block',
    name: 'Promo Block',
    category: 'promotional',
    description: 'Promotional banner with image, title, and CTA',
    version: 1,
    component: PromoBlock,
    defaultProps: {
      imgSrc: NISSAN_IMAGES.moreBanner,
      imgWidth: 520,
      altText: 'Nissan MORE - Up to 10 Years of Warranty',
      title: 'Nissan MORE',
      subtitle: 'Up to <strong>10 years of warranty</strong> on selected models.',
      ctaText: 'LEARN MORE',
      ctaUrl: 'https://www.nissan.com/more',
      backgroundColor: NISSAN_COLORS.black,
      cardBackgroundColor: NISSAN_COLORS.black,
    },
    fields: [
      { key: 'imgSrc', label: 'Image URL', type: 'image', required: true, group: 'Content' },
      { key: 'title', label: 'Title', type: 'text', group: 'Content' },
      { key: 'subtitle', label: 'Subtitle', type: 'richtext', group: 'Content' },
      { key: 'ctaText', label: 'Button Text', type: 'text', group: 'Content' },
      { key: 'ctaUrl', label: 'Button URL', type: 'url', group: 'Content' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'cta-banner',
    name: 'CTA Banner',
    category: 'promotional',
    description: 'Full-width call-to-action banner',
    version: 1,
    component: CtaBanner,
    defaultProps: {
      headline: 'Take Action Today',
      subtext: 'Visit us or get in touch to learn more.',
      buttonText: 'Get Started',
      buttonUrl: 'https://example.com',
      backgroundColor: '#000000',
      headlineColor: '#ffffff',
      subtextColor: '#cccccc',
      buttonBackgroundColor: '#ffffff',
      buttonTextColor: '#000000',
    },
    fields: [
      { key: 'headline', label: 'Headline', type: 'text', required: true, group: 'Content' },
      { key: 'subtext', label: 'Subtext', type: 'text', group: 'Content' },
      { key: 'buttonText', label: 'Button Text', type: 'text', required: true, group: 'Content' },
      { key: 'buttonUrl', label: 'Button URL', type: 'url', required: true, group: 'Content' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'footer',
    name: 'Footer',
    category: 'layout',
    description: 'Email footer with social links and legal text',
    version: 1,
    component: Footer,
    defaultProps: {
      backgroundColor: NISSAN_COLORS.darkGray,
      logoSrc: NISSAN_IMAGES.logo,
      logoWidth: 160,
      logoAlt: 'Nissan',
      logoUrl: 'https://www.nissan.com',
      socialTitle: 'Connect with us',
      socialLinks: [
        { platform: 'facebook', url: 'https://facebook.com/nissan', iconUrl: NISSAN_SOCIAL_ICONS.facebook },
        { platform: 'instagram', url: 'https://instagram.com/nissan', iconUrl: NISSAN_SOCIAL_ICONS.instagram },
      ],
      showDivider: true,
      legalText: 'Nissan MORE warranty offer valid on selected models. Terms and conditions apply.',
      showLinks: true,
      preferencesUrl: 'https://www.nissan.com/preferences',
      unsubscribeUrl: 'https://www.nissan.com/unsubscribe',
      privacyUrl: 'https://www.nissan.com/privacy',
      copyright: '© 2026 Nissan Motor Corporation. All rights reserved.',
    },
    fields: [
      { key: 'copyright', label: 'Copyright', type: 'text', group: 'Content' },
      { key: 'legalText', label: 'Legal Text', type: 'richtext', group: 'Content' },
      { key: 'unsubscribeUrl', label: 'Unsubscribe URL', type: 'url', group: 'Links' },
      { key: 'privacyUrl', label: 'Privacy URL', type: 'url', group: 'Links' },
      { key: 'preferencesUrl', label: 'Preferences URL', type: 'url', group: 'Links' },
      { key: 'address', label: 'Address', type: 'richtext', group: 'Content' },
      { key: 'phone', label: 'Phone', type: 'text', group: 'Content' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
      { key: 'socialLinks', label: 'Social Links', type: 'json', group: 'Content', advanced: true },
    ],
  },
  {
    id: 'order-card',
    name: 'Order Card',
    category: 'transactional',
    description: 'Dark card with label/value order details',
    version: 1,
    component: OrderCard,
    defaultProps: {
      backgroundColor: '#ffffff',
      cardBackgroundColor: '#333333',
      cardWidth: 520,
      cardBorderRadius: '8px',
      dividerColor: '#555555',
      rows: [
        { label: 'Order Number', value: '#ORD-001' },
        { label: 'Order Date', value: 'January 1, 2026' },
        { label: 'Order Total', value: '<strong>$99.00</strong>' },
      ],
    },
    fields: [
      { key: 'rows', label: 'Order Rows', type: 'json', required: true, group: 'Content', advanced: true },
      { key: 'cardBackgroundColor', label: 'Card Background', type: 'color', group: 'Style' },
      { key: 'backgroundColor', label: 'Section Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'two-col-dual-cta',
    name: '2-Col Dual CTA',
    category: 'product-showcase',
    description: 'Two-column product cards with dual CTAs',
    version: 1,
    component: TwoColDualCta,
    defaultProps: {
      backgroundColor: NISSAN_COLORS.lightGray,
      deskPadding: '20px 40px',
      gutterWidth: 20,
      textAlign: 'center',
      rows: [structuredClone(NISSAN_PRODUCT_DEFAULTS.twoColDualCtaRow)],
    },
    fields: [
      { key: 'rows', label: 'Product Rows', type: 'json', required: true, group: 'Content', advanced: true },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
      { key: 'textAlign', label: 'Text Align', type: 'select', group: 'Layout', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ]},
    ],
  },
  {
    id: 'two-col-stacked',
    name: 'Two Col Stacked',
    category: 'product-showcase',
    description: 'Two-column stacked products with prices',
    version: 1,
    component: TwoColStacked,
    defaultProps: {
      backgroundColor: NISSAN_COLORS.lightGray,
      deskPadding: '20px 40px',
      gutterWidth: 20,
      rows: [structuredClone(NISSAN_PRODUCT_DEFAULTS.twoColStackedRow)],
    },
    fields: [
      { key: 'rows', label: 'Product Rows', type: 'json', required: true, group: 'Content', advanced: true },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'one-col-product',
    name: 'One Col Product',
    category: 'product-showcase',
    description: 'Single-column featured product',
    version: 1,
    component: OneColProduct,
    defaultProps: {
      backgroundColor: NISSAN_COLORS.lightGray,
      contentWidth: 520,
      contentAlign: 'center',
      textAlign: 'center',
      rows: [structuredClone(NISSAN_PRODUCT_DEFAULTS.oneColProductRow)],
    },
    fields: [
      { key: 'rows', label: 'Products', type: 'json', required: true, group: 'Content', advanced: true },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
      { key: 'textAlign', label: 'Text Align', type: 'select', group: 'Layout', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ]},
    ],
  },
  {
    id: 'three-col-icon',
    name: 'Three Col Icon',
    category: 'promotional',
    description: 'Three-column icon feature grid',
    version: 1,
    component: ThreeColIcon,
    defaultProps: {
      backgroundColor: NISSAN_COLORS.white,
      gutterWidth: 20,
      textHeight: 70,
      rows: [structuredClone(NISSAN_PRODUCT_DEFAULTS.threeColIconRow)],
    },
    fields: [
      { key: 'rows', label: 'Feature Rows', type: 'json', required: true, group: 'Content', advanced: true },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'hero-banner',
    name: 'Hero Banner',
    category: 'promotional',
    description: 'Full-width hero image with headline and CTA',
    version: 1,
    component: HeroBanner,
    defaultProps: {
      imgSrc: NISSAN_IMAGES.moreBanner,
      imgWidth: 600,
      altText: 'Nissan MORE - Up to 10 Years of Warranty',
      headline: 'Discover Nissan MORE',
      subheadline: 'Up to 10 years of warranty on selected Nissan models.',
      ctaText: 'Explore Offers',
      ctaUrl: 'https://www.nissan.com/more',
      backgroundColor: NISSAN_COLORS.black,
      contentBackgroundColor: NISSAN_COLORS.white,
      textAlign: 'center',
    },
    fields: [
      { key: 'imgSrc', label: 'Hero Image', type: 'image', required: true, group: 'Content' },
      { key: 'headline', label: 'Headline', type: 'text', group: 'Content' },
      { key: 'subheadline', label: 'Subheadline', type: 'text', group: 'Content' },
      { key: 'ctaText', label: 'Button Text', type: 'text', group: 'Content' },
      { key: 'ctaUrl', label: 'Button URL', type: 'url', group: 'Content' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'divider',
    name: 'Divider',
    category: 'layout',
    description: 'Horizontal line separator between sections',
    version: 1,
    component: Divider,
    defaultProps: {
      backgroundColor: '#ffffff',
      lineColor: '#e5e5e5',
      lineHeight: 1,
      deskPadding: '20px 40px',
      width: 520,
    },
    fields: [
      { key: 'lineColor', label: 'Line Color', type: 'color', group: 'Style' },
      { key: 'lineHeight', label: 'Line Height (px)', type: 'number', group: 'Layout' },
      { key: 'width', label: 'Line Width (px)', type: 'number', group: 'Layout' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'button-row',
    name: 'Button Row',
    category: 'promotional',
    description: 'Primary and optional secondary CTA buttons',
    version: 1,
    component: ButtonRow,
    defaultProps: {
      primaryText: 'Get Started',
      primaryUrl: 'https://example.com',
      secondaryText: 'Learn More',
      secondaryUrl: 'https://example.com/about',
      backgroundColor: '#ffffff',
      align: 'center',
      primaryBackgroundColor: '#000000',
      primaryTextColor: '#ffffff',
      secondaryBackgroundColor: '#ffffff',
      secondaryTextColor: '#000000',
    },
    fields: [
      { key: 'primaryText', label: 'Primary Button', type: 'text', required: true, group: 'Content' },
      { key: 'primaryUrl', label: 'Primary URL', type: 'url', required: true, group: 'Content' },
      { key: 'secondaryText', label: 'Secondary Button', type: 'text', group: 'Content' },
      { key: 'secondaryUrl', label: 'Secondary URL', type: 'url', group: 'Content' },
      { key: 'align', label: 'Alignment', type: 'select', group: 'Layout', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ]},
      { key: 'primaryBackgroundColor', label: 'Primary BG', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'image-block',
    name: 'Image Block',
    category: 'layout',
    description: 'Standalone full-width or inset image with optional link',
    version: 1,
    component: ImageBlock,
    defaultProps: {
      imgSrc: NISSAN_IMAGES.qashqai,
      imgWidth: 520,
      altText: 'Nissan Qashqai',
      url: 'https://www.nissan.com/qashqai',
      backgroundColor: NISSAN_COLORS.white,
      align: 'center',
    },
    fields: [
      { key: 'imgSrc', label: 'Image URL', type: 'image', required: true, group: 'Content' },
      { key: 'mobileSrc', label: 'Mobile Image URL', type: 'image', group: 'Content', advanced: true },
      { key: 'imgWidth', label: 'Width (px)', type: 'number', group: 'Layout' },
      { key: 'altText', label: 'Alt Text', type: 'text', group: 'Content' },
      { key: 'url', label: 'Link URL', type: 'url', group: 'Content' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'testimonial',
    name: 'Testimonial',
    category: 'newsletter',
    description: 'Customer quote with author name and optional avatar',
    version: 1,
    component: Testimonial,
    defaultProps: {
      quote: 'This product exceeded all my expectations. Highly recommended!',
      authorName: 'Jane Smith',
      authorTitle: 'Verified Customer',
      avatarSrc: 'https://placehold.co/56x56/e2e8f0/64748b?text=JS',
      backgroundColor: '#f7f8f8',
      cardBackgroundColor: '#ffffff',
    },
    fields: [
      { key: 'quote', label: 'Quote', type: 'richtext', required: true, group: 'Content' },
      { key: 'authorName', label: 'Author Name', type: 'text', required: true, group: 'Content' },
      { key: 'authorTitle', label: 'Author Title', type: 'text', group: 'Content' },
      { key: 'avatarSrc', label: 'Avatar URL', type: 'image', group: 'Content' },
      { key: 'cardBackgroundColor', label: 'Card Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'text-block',
    name: 'Text Block',
    category: 'newsletter',
    description: 'Flexible rich text content section',
    version: 1,
    component: TextBlock,
    defaultProps: {
      content: '<p>Add your content here. Supports <strong>HTML</strong> formatting.</p>',
      backgroundColor: '#ffffff',
      deskPadding: '20px 40px',
      textAlign: 'left',
      fontSize: '16px',
      lineHeight: '26px',
      color: '#333333',
    },
    fields: [
      { key: 'content', label: 'Content', type: 'richtext', required: true, group: 'Content' },
      { key: 'textAlign', label: 'Alignment', type: 'select', group: 'Layout', options: [
        { label: 'Left', value: 'left' },
        { label: 'Center', value: 'center' },
        { label: 'Right', value: 'right' },
      ]},
      { key: 'fontSize', label: 'Font Size', type: 'text', group: 'Style' },
      { key: 'color', label: 'Text Color', type: 'color', group: 'Style' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'spacer',
    name: 'Spacer',
    category: 'layout',
    description: 'Vertical whitespace between sections',
    version: 1,
    component: Spacer,
    defaultProps: {
      height: 32,
      backgroundColor: '#ffffff',
    },
    fields: [
      { key: 'height', label: 'Height (px)', type: 'number', required: true, group: 'Layout' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
    ],
  },
  {
    id: 'stats-row',
    name: 'Stats Row',
    category: 'promotional',
    description: 'Three-column statistics highlight row',
    version: 1,
    component: StatsRow,
    defaultProps: {
      stats: [
        { value: '10K+', label: 'Happy Customers' },
        { value: '99%', label: 'Satisfaction Rate' },
        { value: '24/7', label: 'Support' },
      ],
      backgroundColor: '#f7f8f8',
      defaultValueColor: '#000000',
      labelColor: '#666666',
    },
    fields: [
      { key: 'stats', label: 'Statistics', type: 'json', required: true, group: 'Content', advanced: true,
        helpText: 'Array of 3 items: { value, label, valueColor? }' },
      { key: 'backgroundColor', label: 'Background', type: 'color', group: 'Style' },
      { key: 'defaultValueColor', label: 'Value Color', type: 'color', group: 'Style' },
    ],
  },
];

export const componentRegistry = new Map(
  componentDefinitions.map((def) => [def.id, def])
);
